# Generated by Django 3.2.5 on 2021-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='island',
            field=models.TextField(blank=True, null=True),
        ),
    ]
