# Generated by Django 3.2.5 on 2021-08-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_article_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='location',
        ),
    ]
